Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,10 +31,15 @@ jobs:
           SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         run: |
+          set -e
           eval $(ssh-agent -s)
           echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
           mkdir -p ~/.ssh
           touch ~/.ssh/known_hosts
           ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
-          ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP -p $SERVER_PORT 'rm -rf ~/delta-gain-frontend/*'
-          scp -r dist/* $SERVER_USERNAME@$SERVER_IP:~/delta-gain-frontend/
+          echo "Known hosts file:"
+          cat ~/.ssh/known_hosts
+          echo "Removing existing frontend directory on server"
+          ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP -p $SERVER_PORT 'rm -rf ~/delta-gain-frontend/*' || (echo "Failed to remove existing frontend directory" && exit 1)
+          echo "Copying new build to server"
+          scp -r dist/* $SERVER_USERNAME@$SERVER_IP:~/delta-gain-frontend/ || (echo "Failed to copy new build to server" && exit 1)
